import { Structure } from "./(components)/Structure";
import "./globals.css";
import { ThemeProvider } from "next-themes";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ThemeProvider attribute="class">
          <Structure>{children}</Structure>
        </ThemeProvider>
      </body>
    </html>
  );
}
